# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

matern_5_2_funct <- function(d, beta_i) {
    .Call('_RobustGaSP2_matern_5_2_funct', PACKAGE = 'RobustGaSP2', d, beta_i)
}

matern_3_2_funct <- function(d, beta_i) {
    .Call('_RobustGaSP2_matern_3_2_funct', PACKAGE = 'RobustGaSP2', d, beta_i)
}

pow_exp_funct <- function(d, beta_i, alpha_i) {
    .Call('_RobustGaSP2_pow_exp_funct', PACKAGE = 'RobustGaSP2', d, beta_i, alpha_i)
}

periodic_gauss_funct <- function(d, beta_i) {
    .Call('_RobustGaSP2_periodic_gauss_funct', PACKAGE = 'RobustGaSP2', d, beta_i)
}

periodic_exp_funct <- function(d, beta_i) {
    .Call('_RobustGaSP2_periodic_exp_funct', PACKAGE = 'RobustGaSP2', d, beta_i)
}

matern_5_2_deriv <- function(R0_i, R, beta_i) {
    .Call('_RobustGaSP2_matern_5_2_deriv', PACKAGE = 'RobustGaSP2', R0_i, R, beta_i)
}

matern_3_2_deriv <- function(R0_i, R, beta_i) {
    .Call('_RobustGaSP2_matern_3_2_deriv', PACKAGE = 'RobustGaSP2', R0_i, R, beta_i)
}

pow_exp_deriv <- function(R0_i, R, beta_i, alpha_i) {
    .Call('_RobustGaSP2_pow_exp_deriv', PACKAGE = 'RobustGaSP2', R0_i, R, beta_i, alpha_i)
}

periodic_gauss_deriv <- function(R0_i, R, beta_i) {
    .Call('_RobustGaSP2_periodic_gauss_deriv', PACKAGE = 'RobustGaSP2', R0_i, R, beta_i)
}

periodic_exp_deriv <- function(R0_i, R, beta_i) {
    .Call('_RobustGaSP2_periodic_exp_deriv', PACKAGE = 'RobustGaSP2', R0_i, R, beta_i)
}

separable_kernel <- function(R0, beta, kernel_type, alpha) {
    .Call('_RobustGaSP2_separable_kernel', PACKAGE = 'RobustGaSP2', R0, beta, kernel_type, alpha)
}

separable_multi_kernel <- function(R0, beta, kernel_type, alpha) {
    .Call('_RobustGaSP2_separable_multi_kernel', PACKAGE = 'RobustGaSP2', R0, beta, kernel_type, alpha)
}

separable_multi_kernel_pred_periodic <- function(R0, beta, kernel_type, alpha, perid_const) {
    .Call('_RobustGaSP2_separable_multi_kernel_pred_periodic', PACKAGE = 'RobustGaSP2', R0, beta, kernel_type, alpha, perid_const)
}

euclidean_distance <- function(input1, input2) {
    .Call('_RobustGaSP2_euclidean_distance', PACKAGE = 'RobustGaSP2', input1, input2)
}

log_marginal_lik <- function(param, nugget, nugget_est, R0, X, zero_mean, output, kernel_type, alpha) {
    .Call('_RobustGaSP2_log_marginal_lik', PACKAGE = 'RobustGaSP2', param, nugget, nugget_est, R0, X, zero_mean, output, kernel_type, alpha)
}

log_profile_lik <- function(param, nugget, nugget_est, R0, X, zero_mean, output, kernel_type, alpha) {
    .Call('_RobustGaSP2_log_profile_lik', PACKAGE = 'RobustGaSP2', param, nugget, nugget_est, R0, X, zero_mean, output, kernel_type, alpha)
}

log_approx_ref_prior <- function(param, nugget, nugget_est, CL, a, b) {
    .Call('_RobustGaSP2_log_approx_ref_prior', PACKAGE = 'RobustGaSP2', param, nugget, nugget_est, CL, a, b)
}

log_marginal_lik_deriv <- function(param, nugget, nugget_est, R0, X, zero_mean, output, kernel_type, alpha) {
    .Call('_RobustGaSP2_log_marginal_lik_deriv', PACKAGE = 'RobustGaSP2', param, nugget, nugget_est, R0, X, zero_mean, output, kernel_type, alpha)
}

log_profile_lik_deriv <- function(param, nugget, nugget_est, R0, X, zero_mean, output, kernel_type, alpha) {
    .Call('_RobustGaSP2_log_profile_lik_deriv', PACKAGE = 'RobustGaSP2', param, nugget, nugget_est, R0, X, zero_mean, output, kernel_type, alpha)
}

log_approx_ref_prior_deriv <- function(param, nugget, nugget_est, CL, a, b) {
    .Call('_RobustGaSP2_log_approx_ref_prior_deriv', PACKAGE = 'RobustGaSP2', param, nugget, nugget_est, CL, a, b)
}

log_ref_marginal_post <- function(param, nugget, nugget_est, R0, X, zero_mean, output, kernel_type, alpha) {
    .Call('_RobustGaSP2_log_ref_marginal_post', PACKAGE = 'RobustGaSP2', param, nugget, nugget_est, R0, X, zero_mean, output, kernel_type, alpha)
}

construct_rgasp <- function(beta, nu, R0, X, zero_mean, output, kernel_type, alpha) {
    .Call('_RobustGaSP2_construct_rgasp', PACKAGE = 'RobustGaSP2', beta, nu, R0, X, zero_mean, output, kernel_type, alpha)
}

pred_rgasp <- function(beta, nu, input, X, zero_mean, output, testing_input, X_testing, L, LX, theta_hat, sigma2_hat, q_025, q_975, r0, kernel_type, alpha, method, interval_data) {
    .Call('_RobustGaSP2_pred_rgasp', PACKAGE = 'RobustGaSP2', beta, nu, input, X, zero_mean, output, testing_input, X_testing, L, LX, theta_hat, sigma2_hat, q_025, q_975, r0, kernel_type, alpha, method, interval_data)
}

generate_predictive_mean_cov <- function(beta, nu, input, X, zero_mean, output, testing_input, X_testing, L, LX, theta_hat, sigma2_hat, rr0, r0, kernel_type, alpha, method, sample_data) {
    .Call('_RobustGaSP2_generate_predictive_mean_cov', PACKAGE = 'RobustGaSP2', beta, nu, input, X, zero_mean, output, testing_input, X_testing, L, LX, theta_hat, sigma2_hat, rr0, r0, kernel_type, alpha, method, sample_data)
}

log_marginal_lik_ppgasp <- function(param, nugget, nugget_est, R0, X, zero_mean, output, kernel_type, alpha) {
    .Call('_RobustGaSP2_log_marginal_lik_ppgasp', PACKAGE = 'RobustGaSP2', param, nugget, nugget_est, R0, X, zero_mean, output, kernel_type, alpha)
}

log_profile_lik_ppgasp <- function(param, nugget, nugget_est, R0, X, zero_mean, output, kernel_type, alpha) {
    .Call('_RobustGaSP2_log_profile_lik_ppgasp', PACKAGE = 'RobustGaSP2', param, nugget, nugget_est, R0, X, zero_mean, output, kernel_type, alpha)
}

log_ref_marginal_post_ppgasp <- function(param, nugget, nugget_est, R0, X, zero_mean, output, kernel_type, alpha) {
    .Call('_RobustGaSP2_log_ref_marginal_post_ppgasp', PACKAGE = 'RobustGaSP2', param, nugget, nugget_est, R0, X, zero_mean, output, kernel_type, alpha)
}

log_marginal_lik_deriv_ppgasp <- function(param, nugget, nugget_est, R0, X, zero_mean, output, kernel_type, alpha) {
    .Call('_RobustGaSP2_log_marginal_lik_deriv_ppgasp', PACKAGE = 'RobustGaSP2', param, nugget, nugget_est, R0, X, zero_mean, output, kernel_type, alpha)
}

log_profile_lik_deriv_ppgasp <- function(param, nugget, nugget_est, R0, X, zero_mean, output, kernel_type, alpha) {
    .Call('_RobustGaSP2_log_profile_lik_deriv_ppgasp', PACKAGE = 'RobustGaSP2', param, nugget, nugget_est, R0, X, zero_mean, output, kernel_type, alpha)
}

construct_ppgasp <- function(beta, nu, R0, X, zero_mean, output, kernel_type, alpha) {
    .Call('_RobustGaSP2_construct_ppgasp', PACKAGE = 'RobustGaSP2', beta, nu, R0, X, zero_mean, output, kernel_type, alpha)
}

pred_ppgasp <- function(beta, nu, input, X, zero_mean, output, testing_input, X_testing, L, LX, theta_hat, sigma2_hat, q_025, q_975, r0, kernel_type, alpha, method, interval_data) {
    .Call('_RobustGaSP2_pred_ppgasp', PACKAGE = 'RobustGaSP2', beta, nu, input, X, zero_mean, output, testing_input, X_testing, L, LX, theta_hat, sigma2_hat, q_025, q_975, r0, kernel_type, alpha, method, interval_data)
}

test_const_column <- function(d) {
    .Call('_RobustGaSP2_test_const_column', PACKAGE = 'RobustGaSP2', d)
}

